export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const ADD_TO_SAVE_FOR_LATER = "ADD_TO_SAVE_FOR_LATER";
export const REMOVE_FROM_SAVE_FOR_LATER = "REMOVE_FROM_SAVE_FOR_LATER";
